### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/fart-detector#3]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
Cover added. Components incoming.

@davidhoness can you list any diagrams you need Sam to do here please?

**Comment by bennuttall** [comment]
Code files need moving to code folder @LornaLynch
