### ISSUE TITLE
Code not visible

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/fart-detector#7]
Code block at lines 184-186 is too long to view on the website, and I can't find a way to make the text wrap. Any ideas?

**Comment by bennuttall** [comment]
Are you not seeing a horizontal scrollbar?

**Comment by LornaLynch** [comment]
No, not on the website. It just cuts off at the margin (after ...master/sound). I'm using Firefox: I've just checked Chrome and the text wraps there, but not in my browser.
