### ISSUE TITLE
DAC or ADC?

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/fart-detector#9]
This may be a stupid question, but should the DAC not be an ADC, as it's converting analogue to digital, and not the other way around?

**Comment by davidhoness** [comment]
No it is a DAC. The ladder DAC takes a number between 0 and 15 in binary and enables / disabled the four resistors to affect how much voltage is siphoned off to ground. So it's not measuring an analogue signal (which would be an ADC) it's setting the level of an analogue signal based on a digital number.

**Comment by LornaLynch** [comment]
Thanks! Sorry: I'm not a scientist, as you may have noticed. Thanks for clarifying: I just wanted to be sure.

**Comment by martinohanlon** [comment]
Closing.
